main/urls.py
from django.urls import path, re_path

from . import views
from main import views

handler404 = 'main.views.errors.response_404'

urlpatterns = [
    path('', views.home.index, name='index'),
    path('about/faqs',views.about.faqs,name="about_faqs"),
    path('about/terms',views.about.terms,name="about_terms"),
    path('about/privacy',views.about.privacy,name="about_privacy"),
    path('about/contact',views.about.contact,name="about_contact"),
    path('payment/price-check',views.payment.price_check,name="price_check"),
    path('payment/confirm/<str:assignment_id>',views.payment.confirm,name="payment_confirm"),
    path('payment/add/<str:assignment_id>',views.payment.add,name="payment_add"),
    path('payment/set-price/<str:assignment_id>/<int:price>',views.payment.set,name="set_price"),
    path('payment/calculate/',views.payment.calculate,name="calculate"),
    path('assignment/<str:assignment_id>/upload/<str:cookie>',views.assignment.upload,name="assignment_upload"),
    path('assignment/uploaded/<str:assignment_id>',views.assignment.uploaded,name="assignment_uploaded"),
    path('assignment/paid_additional/<str:assignment_id>',views.assignment.paid_additional,name="paid_additional"),
    path('assignment/cancel/<str:pub_id>',views.assignment.cancel,name="cancel"),
    path('assignment/cancel_user/<str:pub_id>/<str:cookie>',views.assignment.cancel_user,name="cancel"),
    path('assignment/add_payment/<str:pub_id>',views.assignment.add_payment,name="add_payment"),
    path('assignment/upload_answers/<str:pub_id>',views.assignment.upload_answers,name="upload_answers"),
    path('assignment/refund_assign/<str:pub_id>',views.assignment.refund_assign,name="refund_assign"),
    path('stripe/webhook', views.xt_stripe.webhook, name="stripe_webhook"),
    path('stripe/create_session/<str:pub_id>',views.xt_stripe.create_session, name="create_stripe_session"),
    path('stripe/create_session_add/<str:pub_id>',views.xt_stripe.create_session_add, name="create_stripe_session"),
    path('coinbase/webhook', views.coinbase.webhook, name="coinbase_webhook"),
    path('coinbase/create_charge/<str:pub_id>', views.coinbase.create_charge, name="create_crypto"),
    path('x-bot/talk',views.x_bot.talk, name="x-bot"),
    path('help/statistics',views.subject.statistics, name="statistics"),
    path('help/programming-database',views.subject.programming, name="programming"),
    path('help/mathematics',views.subject.mathematics, name="mathematics"),
    path('help/<str:subject>',views.help.index, name="help"),
    path('assignment/review/<str:pub_id>/<str:cookie>',views.assignment.review, name="review"),
]

xt/urls.py
from django.urls import include,re_path
from django.contrib import admin


urlpatterns = [
    re_path(r'^', include('main.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^paypal-ipn', include('paypal.standard.ipn.urls')),
]

main/models.py
from django.db import models
import main.utils as main_utils
from django.contrib.auth.models import User
from django.utils.html import format_html
from datetime import datetime, timezone
import main.settings as main_settings


# Create your models here.
class Address(models.Model):
    address1 = models.CharField(max_length=50)
    address2 = models.CharField(max_length=50)
    city = models.CharField(max_length=25)
    zip_code = models.CharField(max_length=8)
    country_code = models.CharField(max_length=2)
    created_on = models.DateTimeField(auto_now_add=True,editable=False)

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(unique=True,verbose_name="Email")
    address = models.ForeignKey(Address,on_delete=models.CASCADE,null=True)
    phone = models.CharField(max_length=12,null=True)
    timezone = models.CharField(max_length=25,null=True,blank=True)
    created_on = models.DateTimeField(auto_now_add=True,editable=False)
    def __str__(self):
        return self.email

class Tutor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField(null=True,unique=True,verbose_name="Email",blank=True)
    address = models.ForeignKey(Address,on_delete=models.CASCADE,null=True,blank=True)
    phone = models.CharField(max_length=12,null=True,blank=True)
    pan = models.CharField(max_length=10,null=True,blank=True)
    bank_name = models.CharField(null=True,max_length=50,blank=True)
    account_no = models.CharField(max_length=25,null=True,blank=True)
    ifsc_code = models.CharField(max_length=12,null=True,blank=True)
    is_active = models.BooleanField(default=True,blank=True)
    created_on = models.DateTimeField(auto_now_add=True,editable=False)
    def __str__(self):
        return self.name
def assignment_path(instance, filename):
    return 'assignments/{0}/{1}'.format(instance.public_id, filename)

class Assignment(models.Model):
    public_id = models.BigIntegerField(unique=True)
    year_month = models.IntegerField(default=0)
    email = models.EmailField(verbose_name="Email")
    student = models.ForeignKey(Student,null=True, on_delete=models.PROTECT)
    assigned_to = models.ForeignKey(Tutor,null=True,blank=True,on_delete=models.PROTECT)
    subject = models.CharField(max_length=25,choices=main_settings.SUBJECT_CHOICES)
    grade = models.CharField(max_length=25, choices=main_settings.GRADE_CHOICES,)
    duration = models.IntegerField()
    num_questions = models.IntegerField()
    short_answer = models.BooleanField()
    price = models.DecimalField(max_digits=8,decimal_places=2)
    tutor_payment = models.DecimalField(max_digits=8,decimal_places=2,default=0)
    paid = models.DecimalField(default=0,max_digits=8,decimal_places=2)
    paid_on = models.DateTimeField(null=True,blank=True)
    refund = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    refund_additional = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    additional_payment = models.DecimalField(default=0,max_digits=8,decimal_places=2)
    add_payment_reason = models.CharField(null=True,blank=True, max_length=64, choices=main_settings.ADD_PAY_REASONS)
    add_payment_note = models.CharField(null=True, blank=True, max_length=512,help_text='Make sure that this note is saved before requesting payment.')
    additional_payment_on = models.DateTimeField(null=True,blank=True)
    currency = models.CharField(max_length=4,default='USD')
    created_on = models.DateTimeField(auto_now_add=True,editable=False)
    submitted_on = models.DateTimeField(null=True)
    answered_on = models.DateTimeField(null=True)
    due_on = models.DateTimeField(null=True)
    solution_on = models.DateTimeField(null=True,blank=True)
    status = models.CharField(default='NEW', max_length=32, choices=main_settings.ASSIGNMENT_STATUSES,)
    question_text = models.TextField(null=True, blank=True)
    answer_text = models.TextField(null=True, blank=True)
    question_note = models.TextField(null=True,blank=True)
    answer_note = models.TextField(null=True,blank=True)
    question_file = models.FileField(null=True, blank=True ,upload_to=assignment_path)
    answer_file = models.FileField(null=True, blank=True ,upload_to=assignment_path)
    cs_remark = models.CharField(verbose_name="remark",null=True,blank=True,max_length=100)
    cancellation_reason = models.CharField(null=True, blank=True, max_length=64, choices=main_settings.CANCELLATION_REASONS)
    IP = models.CharField(max_length=32,null=True)
    cookie = models.CharField(max_length=32, null=True)
    #@property
    def refunded(self):
        if (self.paid + self.additional_payment + self.refund + self.refund_additional <= 0):
            return True
        else:
            return False
    refunded.boolean = True
    refunded.short_description = "Refunded"

    def total_paid(self):
        return self.paid + self.additional_payment + self.refund + self.refund_additional

    def full_payment(self):
        if (self.paid + self.additional_payment >= self.price):
            return True
        else:
            return False
    full_payment.boolean = True
    full_payment.short_description = "Paid"
    def color(self):
        if self.due_on is None:
            color_name = '83786F'
        else:
            nw = datetime.now(timezone.utc)
            t_delta = self.due_on - nw
            min = t_delta.days * 24 * 60 + t_delta.seconds // 60
            hr_left = min // 60
            color_name =  '008000'
            if (hr_left < 0.75*self.duration):
                color_name = 'FFC300'
            if (hr_left < 0.5*self.duration):
                color_name = 'FF8633'
            if (hr_left < 0.25*self.duration):
                color_name = 'C70039'
        return format_html('<span style="color: #{};">&#x2b24;</span>',color_name)
    def due_in(self):
        if self.due_on is None:
            return '---'
        nw = datetime.now(timezone.utc)
        t_delta = self.due_on - nw
        min = t_delta.days * 24* 60 +  t_delta.seconds // 60
        if min < 0:
            txt = "-"
            min = -1 * min
        else:
            txt = ""
        hr = min // 60
        min = min % 60
        txt = txt + str(hr) + " hrs, " + str(min) + " min"
        return txt
    def payment_provider(self):
        try:
            payment = Payment.objects.get(invoice=self.public_id)
            if self.additional_payment == 0:
                return payment.provider
            else:
                add_pmt = Payment.objects.get(invoice=str(self.public_id)+'-ADD')
                return payment.provider + ' + ' + add_pmt.provider
        except Payment.DoesNotExist:
            return 'NA'

    def __str__(self):
        return str(self.public_id)

class Payment(models.Model):
    invoice = models.CharField(max_length=32, unique=True)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    currency = models.CharField(max_length=4, default='USD')
    refund = models.DecimalField(default=0,max_digits=8, decimal_places=2)
    refunded_on = models.DateTimeField(null=True, blank=True)
    provider = models.CharField(max_length=32,default='paypal')
    gid = models.CharField(max_length=64,null=True, blank=True, help_text='gateway_id', db_index=True)
    status = models.IntegerField(default=0)
    details = models.TextField(null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True, editable=False)

class PriceCheck(models.Model):
    email = models.EmailField(null=True,verbose_name="Email")
    subject = models.CharField(max_length=25,choices=main_settings.SUBJECT_CHOICES,default=main_settings.DEFAULT_SUBJECT,verbose_name="Subject")
    grade = models.CharField(max_length=25, choices=main_settings.GRADE_CHOICES, default=main_settings.DEFAULT_GRADE,verbose_name="Grade")
    duration = models.IntegerField(choices=main_settings.DURATION_CHOICES,default=main_settings.DEFAULT_DURATION, verbose_name="Timeline")
    num_questions = models.IntegerField(default=1,verbose_name="Number of Questions")
    short_answer = models.BooleanField(default=False,verbose_name="<b>Only Answer</b> (Without Solution Steps)")
    price = models.DecimalField(max_digits=8, decimal_places=2)
    currency = models.CharField(max_length=3, default='USD')
    cookie = models.CharField(max_length=32,null=True)
    created_date = models.DateTimeField(auto_now_add=True,editable=False)
    def calculate_price(self):
        price_t = main_settings.BASE_PRICE
        if self.short_answer == True:
            price_t *= main_settings.SHORT_ANSWER_FACTOR
        if self.num_questions >= 5:
            price_t *= main_settings.BULK_FACTOR
        price_t *= main_settings.CURRENCIES[self.currency]['value']
        price_t *= main_settings.SUBJECTS[self.subject]['weight']
        price_t *= main_settings.DURATIONS[self.duration]['weight']
        price_t = int(price_t * main_settings.GRADES[self.grade]['weight'])
        price_t *= self.num_questions
        self.price = int(price_t)
        return int(self.price)

class Invoice(models.Model):
    pub_id = models.CharField(max_length=32, unique=True)
    tutor = models.ForeignKey(Tutor, on_delete=models.PROTECT)
    total = models.DecimalField(default=0, max_digits=9,decimal_places=2,)
    year_month = models.PositiveIntegerField()
    note = models.CharField(max_length=512)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return str(self.year_month) + "-" + self.tutor.name.replace(" ","_")
    def calculate_total(self):
        assigns = Assignment.objects.filter(assigned_to=self.tutor)

class Review(models.Model):
    assign = models.ForeignKey(Assignment, on_delete=models.PROTECT, unique=True)
    rating = models.IntegerField(default=0)
    review_txt = models.CharField(max_length=512)

main/views/about.py
from django.conf import settings
from django.shortcuts import render
from django.core import mail
from django.template.loader import render_to_string
from django.http import HttpResponse
site_settings = settings.SITE_SETTINGS




def faqs(request):
    from main.utils.faq import faqs
    meta = {'title': 'Frequently Asked Questions (FAQs) | XpressTutor.com',
            'description': 'These are frequently asked questions about XpressTutor.com services. Feel free to send an email to reach out to our support page if you have any query.',
            'keywords': 'faqs, XpressTutor faqs, XpressTutor help, xpress tutor faqs'
            }
    context = {'site_settings':site_settings,'meta':meta,'faqs':faqs}
    return render(request, 'main/about/faq.html', context)
def terms(request):
    meta = {'title':'Terms of Use | XpressTutor.com',
            'keyword':'terms of use, xpresstutor terms, xpress tutor terms',
            'description':'Terms of Use for XpressTutor.com'}
    context = {'site_settings':site_settings,'meta':meta}
    return render(request, 'main/about/terms.html', context)
def privacy(request):
    meta = {'title':'Privacy Policy | XpressTutor.com',
            'keyword':'privacy policy xpresstutor, xpress tutor privacy policy',
            'description':'Privacy policy of XpressTutor.com'}
    context = {'site_settings':site_settings,'meta':meta}
    return render(request, 'main/about/privacy.html', context)
def contact(request):
    from main.forms import ContactForm
    from django.core.mail import send_mail
    from django.contrib import messages
    captcha_key = settings.NORECAPTCHA_SITE_KEY
    meta = {'title':'Contact Us | XpressTutor.com',
            'description':'You can fill in the contact form. We will get back to you in 4-8 hrs.',
            'keywords':'conatct us, contact XpressTutor, contact Xpress Tutor'
            }
    if request.method == 'POST':
        if not 'g-recaptcha-response' in request.POST:
            return HttpResponse('Bad Request')
        form = ContactForm(request.POST,label_suffix=':')
        if form.is_valid():
            name = form.cleaned_data['name']
            from_email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            subject = site_settings['name']+": Contact mail from "+ name
            # Recaptcha settings
            import requests
            recaptcha_response = request.POST['g-recaptcha-response']
            data = {
                'secret': settings.NORECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
            result = r.json()
            if result['success']:
                context = {'name':name,'email':from_email,'message':message}
                msg_plain = name + '\n' + from_email + '\n' + message
                msg_html = render_to_string('main/email/contact.html', context)
                to_emails = [settings.SUPPORT_EMAIL]
                reply_tos = [from_email]
                msg = mail.EmailMessage(subject=subject,body=msg_html,from_email=from_email,to=to_emails,reply_to=reply_tos)
                msg.content_subtype = "html"
                msg.send()
                form = ContactForm(label_suffix=':')
                messages.add_message(request, messages.SUCCESS, 'Your message has been successfully sent.')
            # Save the data
            else:
                messages.add_message(request, messages.ERROR, 'Invalid reCAPTCHA! Please try again.')
    else:
        form = ContactForm(label_suffix=':')
    context = {'site_settings':site_settings,'meta':meta,'form':form,'captcha_key':captcha_key}
    return render(request, 'main/about/contact.html', context)

main/views/errors.py
from django.shortcuts import render
from django.conf import settings

# HTTP Error 404
def response_404(request,exception):
    site_settings = settings.SITE_SETTINGS
    meta = {'title':'Contact Us',
            'keywords':'contact '+ site_settings['name'],
            'description':'You can use this page to contact '+site_settings['name']}
    context = {'site_settings': site_settings, 'meta': meta}
    response = render(request,'main/errors/404.html',context)
    response.status_code = 404
    return response

main/views/help.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404


SUBJECT_MAP = {'statistics':'stat',
               'mathematics':'math',
               'programming-database':'prog',
               'engineering':'engg',
               'management-finance':'mgmt',
               'physics':'phy',
               'economics':'eco',
               'chemistry':'chem',
               'other':'stat'}
def index(request, subject):
    if subject in SUBJECT_MAP:
        sm = SUBJECT_MAP[subject]
    else:
        sm = 'stat'
    return redirect('/payment/price-check?s='+sm)

main/templates/main/payment/price-check.html
{% extends "main/base.html" %}
{% load widget_tweaks %}
{% block content %}
        {% include 'main/navbar_light.html' %}

        <!-- Start Contact -->
        <section class="section">
            <div class="container">
                <div class="row mt-100">
                    <div class="col-lg-7 col-md-6 col-12 mt-4 pt-2">
                        <div class="card rounded border-0 shadow">
                            <div class="bg-light p-4 text-center rounded-top">
                                <h4 class="mb-0 card-title text-primary">Price Calculator</h4>
                            </div>

                            <div class="card-body">
                                <form id ="price-check-form" method="post" action="">
                                    {% csrf_token %}

                                    <div class="row">
                                        <div id="message col-md-12">
                                            {% include 'main/flash_message.html' %}
                                        </div>
                                        <div class="col-md-6 mb-3">
                                                <label class="form-label">Subject :</label>
                                                {% render_field form.subject class="form-select"%}
                                        </div><!--end col-->
                                        <div class="col-md-6 mb-3">
                                            <label class="form-label">Grade :</label>
                                            {% render_field form.grade class="form-select"%}
                                        </div><!--end col-->
                                        <div class="col-md-6 mb-3">
                                            <label class="form-label">Grade :</label>
                                                {% render_field form.duration class="form-select"%}
                                        </div><!--end col-->
                                        <div class="col-md-6 mb-3">
                                            <label class="form-label">Number of Questions :</label>
                                                {% render_field form.num_questions class="form-control font-weight-bold" min=1 max=999%}

                                        </div><!--end col-->
                                        <div class="col-md-12 mb-3">
                                            <div class="form-check form-switch">
                                                {% render_field form.short_answer class="form-check-input" type="checkbox" onchange="calculate_price();" %}
                                                <!--input id="id_short_answer" name="short_answer" class="form-check-input" type="checkbox" onchange="calculate_price();"-->
                                                <label class="form-check-label" for="id_short_answer">Only Answer <span class="text-primary">(Without steps)</span></label>
                                            </div>

                                        </div><!--end col-->
                                        <div class="col-md-12 mb-3">
                                            <label class="form-label">Email : </label>
                                                {% render_field form.email class="form-control"%}
                                        </div><!--end col-->
                                    </div><!--end row-->
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <h1> <span id="id_price_label" class="btn btn-secondary mr-3">$10</span> <button type="submit" id="submit" name="send" class="btn btn-primary"><i class="fa fa-upload mr-2"></i>Pay & Upload</button></h1>

                                            <br/>
                                            <span id="id_price_answer" class="badge bg-info mt-1">$8 per answer</span><br/><br/>
                                            {% if user.is_authenticated %}
                                            <small>{{ site_settings.url }}<span id="id_price_link"></span></small>
                                            {% endif %}

                                        </div><!--end col-->

                                    </div><!--end row-->
                                </form><!--end form-->
                            </div>
                        </div>
                    </div><!--end col-->
                    <div class="col-lg-5 col-md-6 col-12 mt-4 pt-2">
                        <div class="card work-process border-0 rounded shadow mb-3">
                            <div class="card-body">
                                <h4 class="title">Check Price</h4>
                                <p class="text-muted para">Quickly check the price using the price calculator, or send an email to <span class="text-primary">support@xpresstutor.com</span> for quote.</p>
                                <ul class="list-unstyled d-flex justify-content-between mb-0 mt-2">
                                    <li class="step h1 mb-0 font-weight-bold">Step 1.</li>
                                    <li class="step-icon"><i class="far fa-check-square fa-3x"></i></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card work-process border-0 rounded shadow mb-3">
                            <div class="card-body">
                                <h4 class="title">Pay & Upload Questions</h4>
                                <p class="text-muted para">Pay and upload the questions. In few cases we may come back for clarification or approval for price revision</p>
                                <ul class="list-unstyled d-flex justify-content-between mb-0 mt-2">
                                    <li class="step h1 mb-0 font-weight-bold">Step 2.</li>
                                    <li class="step-icon"><i class="far fa-square fa-3x"></i></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card work-process border-0 rounded shadow">
                            <div class="card-body">
                                <h4 class="title">Get Answers on Email</h4>
                                <p class="text-muted para">Detailed solution is emailed to you within given timeline. We are happy to help with clarification if any.</p>
                                <ul class="list-unstyled d-flex justify-content-between mb-0 mt-2">
                                    <li class="step h1 mb-0 font-weight-bold">Step 3.</li>
                                    <li class="step-icon"><i class="far fa-square fa-3x"></i></li>
                                </ul>
                            </div>
                        </div>

                    </div><!--end col-->


                </div><!--end row-->
            </div><!--end container-->

        </section>
        {% include 'main/blocks/testimonial.html' %}

{% endblock %}
{% block body_end %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script type="text/javascript">
        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
        });
        function calculate_price() {
            $("#id_price_label").html('<i class="fa fa-spinner"></i>');
            var form_data = {'subject':$('#id_subject').val(),'grade':$('#id_grade').val(),'duration':$('#id_duration').val(),'num_questions':$('#id_num_questions').val(),'short_answer':$('#id_short_answer').is(':checked')};
            var resp = $.post('/payment/calculate/',form_data,function (data) {
                $("#id_price_label").html("$" + data );
                if ($('#id_short_answer').is(':checked')){
                    $("#id_price_answer").html("$" + data / document.getElementById('id_num_questions').value + " per Answer");
                }
                else {
                    $("#id_price_answer").html("$" + data / document.getElementById('id_num_questions').value + " per Answer (with step by step solution)");
                }
                //$("#id_price_answer").html("$" + parseInt(data)/parseInt($("#id_num_questions").value));
            });
            var price = resp.toString();
            s = $('#id_subject').val();
            g = $('#id_grade').val();
            d = $('#id_duration').val();
            n = $('#id_num_questions').val();
            a = "0";
            if ($('#id_short_answer').is(':checked')){
                a = "1"
            }
            url = 'payment/price-check?s='+s + '&g=' + g + '&d=' + d + '&n=' + n + '&a=' + a
            $('#id_price_link').html(url)
        }
        $( document ).ready(function() {
            calculate_price();
        });
    </script>
{% endblock %}