main/urls.py
from django.urls import path, re_path

from . import views
from main import views

handler404 = 'main.views.errors.response_404'

urlpatterns = [
    path('', views.home.index, name='index'),
    path('about/faqs',views.about.faqs,name="about_faqs"),
    path('about/terms',views.about.terms,name="about_terms"),
    path('about/privacy',views.about.privacy,name="about_privacy"),
    path('about/contact',views.about.contact,name="about_contact"),
    path('payment/price-check',views.payment.price_check,name="price_check"),
    path('payment/confirm/<str:assignment_id>',views.payment.confirm,name="payment_confirm"),
    path('payment/add/<str:assignment_id>',views.payment.add,name="payment_add"),
    path('payment/set-price/<str:assignment_id>/<int:price>',views.payment.set,name="set_price"),
    path('payment/calculate/',views.payment.calculate,name="calculate"),
    path('assignment/<str:assignment_id>/upload/<str:cookie>',views.assignment.upload,name="assignment_upload"),
    path('assignment/uploaded/<str:assignment_id>',views.assignment.uploaded,name="assignment_uploaded"),
    path('assignment/paid_additional/<str:assignment_id>',views.assignment.paid_additional,name="paid_additional"),
    path('assignment/cancel/<str:pub_id>',views.assignment.cancel,name="cancel"),
    path('assignment/cancel_user/<str:pub_id>/<str:cookie>',views.assignment.cancel_user,name="cancel"),
    path('assignment/add_payment/<str:pub_id>',views.assignment.add_payment,name="add_payment"),
    path('assignment/upload_answers/<str:pub_id>',views.assignment.upload_answers,name="upload_answers"),
    path('assignment/refund_assign/<str:pub_id>',views.assignment.refund_assign,name="refund_assign"),
    path('stripe/webhook', views.xt_stripe.webhook, name="stripe_webhook"),
    path('stripe/create_session/<str:pub_id>',views.xt_stripe.create_session, name="create_stripe_session"),
    path('stripe/create_session_add/<str:pub_id>',views.xt_stripe.create_session_add, name="create_stripe_session"),
    path('coinbase/webhook', views.coinbase.webhook, name="coinbase_webhook"),
    path('coinbase/create_charge/<str:pub_id>', views.coinbase.create_charge, name="create_crypto"),
    path('x-bot/talk',views.x_bot.talk, name="x-bot"),
    path('help/statistics',views.subject.statistics, name="statistics"),
    path('help/programming-database',views.subject.programming, name="programming"),
    path('help/mathematics',views.subject.mathematics, name="mathematics"),
    path('help/<str:subject>',views.help.index, name="help"),
    path('assignment/review/<str:pub_id>/<str:cookie>',views.assignment.review, name="review"),
]

xt/urls.py
from django.urls import include,re_path
from django.contrib import admin


urlpatterns = [
    re_path(r'^', include('main.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^paypal-ipn', include('paypal.standard.ipn.urls')),
]

main/models.py
from django.db import models
import main.utils as main_utils
from django.contrib.auth.models import User
from django.utils.html import format_html
from datetime import datetime, timezone
import main.settings as main_settings


# Create your models here.
class Address(models.Model):
    address1 = models.CharField(max_length=50)
    address2 = models.CharField(max_length=50)
    city = models.CharField(max_length=25)
    zip_code = models.CharField(max_length=8)
    country_code = models.CharField(max_length=2)
    created_on = models.DateTimeField(auto_now_add=True,editable=False)

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(unique=True,verbose_name="Email")
    address = models.ForeignKey(Address,on_delete=models.CASCADE,null=True)
    phone = models.CharField(max_length=12,null=True)
    timezone = models.CharField(max_length=25,null=True,blank=True)
    created_on = models.DateTimeField(auto_now_add=True,editable=False)
    def __str__(self):
        return self.email

class Tutor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField(null=True,unique=True,verbose_name="Email",blank=True)
    address = models.ForeignKey(Address,on_delete=models.CASCADE,null=True,blank=True)
    phone = models.CharField(max_length=12,null=True,blank=True)
    pan = models.CharField(max_length=10,null=True,blank=True)
    bank_name = models.CharField(null=True,max_length=50,blank=True)
    account_no = models.CharField(max_length=25,null=True,blank=True)
    ifsc_code = models.CharField(max_length=12,null=True,blank=True)
    is_active = models.BooleanField(default=True,blank=True)
    created_on = models.DateTimeField(auto_now_add=True,editable=False)
    def __str__(self):
        return self.name
def assignment_path(instance, filename):
    return 'assignments/{0}/{1}'.format(instance.public_id, filename)

class Assignment(models.Model):
    public_id = models.BigIntegerField(unique=True)
    year_month = models.IntegerField(default=0)
    email = models.EmailField(verbose_name="Email")
    student = models.ForeignKey(Student,null=True, on_delete=models.PROTECT)
    assigned_to = models.ForeignKey(Tutor,null=True,blank=True,on_delete=models.PROTECT)
    subject = models.CharField(max_length=25,choices=main_settings.SUBJECT_CHOICES)
    grade = models.CharField(max_length=25, choices=main_settings.GRADE_CHOICES,)
    duration = models.IntegerField()
    num_questions = models.IntegerField()
    short_answer = models.BooleanField()
    price = models.DecimalField(max_digits=8,decimal_places=2)
    tutor_payment = models.DecimalField(max_digits=8,decimal_places=2,default=0)
    paid = models.DecimalField(default=0,max_digits=8,decimal_places=2)
    paid_on = models.DateTimeField(null=True,blank=True)
    refund = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    refund_additional = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    additional_payment = models.DecimalField(default=0,max_digits=8,decimal_places=2)
    add_payment_reason = models.CharField(null=True,blank=True, max_length=64, choices=main_settings.ADD_PAY_REASONS)
    add_payment_note = models.CharField(null=True, blank=True, max_length=512,help_text='Make sure that this note is saved before requesting payment.')
    additional_payment_on = models.DateTimeField(null=True,blank=True)
    currency = models.CharField(max_length=4,default='USD')
    created_on = models.DateTimeField(auto_now_add=True,editable=False)
    submitted_on = models.DateTimeField(null=True)
    answered_on = models.DateTimeField(null=True)
    due_on = models.DateTimeField(null=True)
    solution_on = models.DateTimeField(null=True,blank=True)
    status = models.CharField(default='NEW', max_length=32, choices=main_settings.ASSIGNMENT_STATUSES,)
    question_text = models.TextField(null=True, blank=True)
    answer_text = models.TextField(null=True, blank=True)
    question_note = models.TextField(null=True,blank=True)
    answer_note = models.TextField(null=True,blank=True)
    question_file = models.FileField(null=True, blank=True ,upload_to=assignment_path)
    answer_file = models.FileField(null=True, blank=True ,upload_to=assignment_path)
    cs_remark = models.CharField(verbose_name="remark",null=True,blank=True,max_length=100)
    cancellation_reason = models.CharField(null=True, blank=True, max_length=64, choices=main_settings.CANCELLATION_REASONS)
    IP = models.CharField(max_length=32,null=True)
    cookie = models.CharField(max_length=32, null=True)
    #@property
    def refunded(self):
        if (self.paid + self.additional_payment + self.refund + self.refund_additional <= 0):
            return True
        else:
            return False
    refunded.boolean = True
    refunded.short_description = "Refunded"

    def total_paid(self):
        return self.paid + self.additional_payment + self.refund + self.refund_additional

    def full_payment(self):
        if (self.paid + self.additional_payment >= self.price):
            return True
        else:
            return False
    full_payment.boolean = True
    full_payment.short_description = "Paid"
    def color(self):
        if self.due_on is None:
            color_name = '83786F'
        else:
            nw = datetime.now(timezone.utc)
            t_delta = self.due_on - nw
            min = t_delta.days * 24 * 60 + t_delta.seconds // 60
            hr_left = min // 60
            color_name =  '008000'
            if (hr_left < 0.75*self.duration):
                color_name = 'FFC300'
            if (hr_left < 0.5*self.duration):
                color_name = 'FF8633'
            if (hr_left < 0.25*self.duration):
                color_name = 'C70039'
        return format_html('<span style="color: #{};">&#x2b24;</span>',color_name)
    def due_in(self):
        if self.due_on is None:
            return '---'
        nw = datetime.now(timezone.utc)
        t_delta = self.due_on - nw
        min = t_delta.days * 24* 60 +  t_delta.seconds // 60
        if min < 0:
            txt = "-"
            min = -1 * min
        else:
            txt = ""
        hr = min // 60
        min = min % 60
        txt = txt + str(hr) + " hrs, " + str(min) + " min"
        return txt
    def payment_provider(self):
        try:
            payment = Payment.objects.get(invoice=self.public_id)
            if self.additional_payment == 0:
                return payment.provider
            else:
                add_pmt = Payment.objects.get(invoice=str(self.public_id)+'-ADD')
                return payment.provider + ' + ' + add_pmt.provider
        except Payment.DoesNotExist:
            return 'NA'

    def __str__(self):
        return str(self.public_id)

class Payment(models.Model):
    invoice = models.CharField(max_length=32, unique=True)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    currency = models.CharField(max_length=4, default='USD')
    refund = models.DecimalField(default=0,max_digits=8, decimal_places=2)
    refunded_on = models.DateTimeField(null=True, blank=True)
    provider = models.CharField(max_length=32,default='paypal')
    gid = models.CharField(max_length=64,null=True, blank=True, help_text='gateway_id', db_index=True)
    status = models.IntegerField(default=0)
    details = models.TextField(null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True, editable=False)

class PriceCheck(models.Model):
    email = models.EmailField(null=True,verbose_name="Email")
    subject = models.CharField(max_length=25,choices=main_settings.SUBJECT_CHOICES,default=main_settings.DEFAULT_SUBJECT,verbose_name="Subject")
    grade = models.CharField(max_length=25, choices=main_settings.GRADE_CHOICES, default=main_settings.DEFAULT_GRADE,verbose_name="Grade")
    duration = models.IntegerField(choices=main_settings.DURATION_CHOICES,default=main_settings.DEFAULT_DURATION, verbose_name="Timeline")
    num_questions = models.IntegerField(default=1,verbose_name="Number of Questions")
    short_answer = models.BooleanField(default=False,verbose_name="<b>Only Answer</b> (Without Solution Steps)")
    price = models.DecimalField(max_digits=8, decimal_places=2)
    currency = models.CharField(max_length=3, default='USD')
    cookie = models.CharField(max_length=32,null=True)
    created_date = models.DateTimeField(auto_now_add=True,editable=False)
    def calculate_price(self):
        price_t = main_settings.BASE_PRICE
        if self.short_answer == True:
            price_t *= main_settings.SHORT_ANSWER_FACTOR
        if self.num_questions >= 5:
            price_t *= main_settings.BULK_FACTOR
        price_t *= main_settings.CURRENCIES[self.currency]['value']
        price_t *= main_settings.SUBJECTS[self.subject]['weight']
        price_t *= main_settings.DURATIONS[self.duration]['weight']
        price_t = int(price_t * main_settings.GRADES[self.grade]['weight'])
        price_t *= self.num_questions
        self.price = int(price_t)
        return int(self.price)

class Invoice(models.Model):
    pub_id = models.CharField(max_length=32, unique=True)
    tutor = models.ForeignKey(Tutor, on_delete=models.PROTECT)
    total = models.DecimalField(default=0, max_digits=9,decimal_places=2,)
    year_month = models.PositiveIntegerField()
    note = models.CharField(max_length=512)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return str(self.year_month) + "-" + self.tutor.name.replace(" ","_")
    def calculate_total(self):
        assigns = Assignment.objects.filter(assigned_to=self.tutor)

class Review(models.Model):
    assign = models.ForeignKey(Assignment, on_delete=models.PROTECT, unique=True)
    rating = models.IntegerField(default=0)
    review_txt = models.CharField(max_length=512)

main/forms.py
from django import forms
from django.forms import ModelForm
from main.models import PriceCheck

class ContactForm(forms.Form):
    name = forms.CharField(min_length=3, max_length=25,widget=forms.TextInput(attrs={'pattern':'[A-Za-z ]*','placeholder':'John Doe','style':'margin-bottom:10px;'}),required=True)
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':'john@example.com','style':'margin-bottom:10px;'}),required=True)
    message = forms.CharField(min_length=10, max_length=500,widget=forms.Textarea(attrs={'rows':4,'placeholder':'your message goes here','style':'margin-bottom:10px;'}),required=True   )

class PriceCheckForm(ModelForm):
    class Meta:
        model = PriceCheck
        fields = ['subject','grade','duration','num_questions','short_answer','email']
    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        self.fields['subject'].widget.attrs = {'onchange':'calculate_price()','style':'margin-bottom:10px;'}
        self.fields['grade'].widget.attrs = {'onchange':'calculate_price()','style':'margin-bottom:10px;'}
        self.fields['duration'].widget.attrs = {'onchange':'calculate_price()','style':'margin-bottom:10px;'}
        self.fields['num_questions'].widget.attrs = {'min':1,'max':999,'onchange':'calculate_price()','style':'margin-bottom:10px;'}
        self.fields['email'].widget.attrs = {'style':'margin-bottom:10px;'}
        self.fields['short_answer'].widget.attrs = {'onchange':'calculate_price()','style':'margin-bottom:10px;'}

class AssignmentUploadForm(forms.Form):
    question_text = forms.CharField(required=False,widget=forms.Textarea(attrs={'rows': 8 }))
    question_note = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': 4}))
    file = forms.FileField(required=False)

class UploadAnswersForm(forms.Form):
    answer_text = forms.CharField(required=False,widget=forms.Textarea(attrs={'rows': 8 }))
    answer_note = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': 4}))
    file = forms.FileField(required=False)

main/views/coinbase.py
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect

from coinbase_commerce.error import WebhookInvalidPayload, SignatureVerificationError
from coinbase_commerce.webhook import Webhook
from coinbase_commerce.client import Client

import main.settings as main_settings
from django.conf import settings
from main.models import Payment, Assignment
from main.views.assignment import fulfill as assign_fulfill, refund as assign_refund



@csrf_exempt
def webhook(request):
    WEBHOOK_SECRET = 'ff09a861-c971-40cc-8183-809519e1b700'

    request_sig = request.headers.get('X-CC-Webhook-Signature', None)
    request_data = request.body.decode('utf-8')
    try:
        # signature verification and event object construction
        event = Webhook.construct_event(request_data, request_sig, WEBHOOK_SECRET)
    except (WebhookInvalidPayload, SignatureVerificationError) as e:
        return Http404(str(e))
    assignment = Assignment.objects.get(public_id=event.data['metadata']['pub_id'])
    if event.type == 'charge:confirmed':
        assign_fulfill(assignment_id=assignment.public_id, amount=assignment.price,  user_name=assignment.email, txn_details=str(event))
        payment = Payment.objects.create(invoice=assignment.public_id, amount=assignment.price, gid=event.data['code'],provider='coinbase', details=str(event))
    print("Received event: id={id}, type={type}".format(id=event.id, type=event.type))
    return HttpResponse('OK')

def create_charge(request, pub_id):
    assignment = Assignment.objects.get(public_id=pub_id)
    client = Client(api_key=main_settings.COINBASE_API_KEY)
    charge_info = {
        "name": "The Sovereign Individual",
        "description": "Mastering the Transition to the Information Age",
        "local_price": {
            "amount": str(assignment.price),
            "currency": "USD"
        },
        "metadata": {
            "pub_id": pub_id,
        },
        "pricing_type": "fixed_price",
        "redirect_url": settings.SITE_SETTINGS['url'] + "assignment/"+str(assignment.public_id)+"/upload/"+assignment.cookie,
        "cancel_url": settings.SITE_SETTINGS['url'] + "payment/confirm/" + str(assignment.public_id),
    }
    charge = client.charge.create(**charge_info)
    return redirect(charge.hosted_url)
    # Get hosted_url, id and code

main/views/errors.py
from django.shortcuts import render
from django.conf import settings

# HTTP Error 404
def response_404(request,exception):
    site_settings = settings.SITE_SETTINGS
    meta = {'title':'Contact Us',
            'keywords':'contact '+ site_settings['name'],
            'description':'You can use this page to contact '+site_settings['name']}
    context = {'site_settings': site_settings, 'meta': meta}
    response = render(request,'main/errors/404.html',context)
    response.status_code = 404
    return response

main/templates/main/about/contact.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
        {% include 'main/navbar_light.html' %}
        <!-- Hero Start -->
        <section class="bg-half bg-light d-table w-100">
            <!--div class="bg-overlay bg-overlay-white"></div-->
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-12 text-center">
                        <div class="page-next-level">
                            <h4 class="title">Contact Us</h4>
                            <div class="page-next">
                                <nav aria-label="breadcrumb" class="d-inline-block">
                                    <ul class="breadcrumb bg-white rounded shadow mb-0">
                                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                                        <li class="breadcrumb-item"><a href="#">About</a></li>
                                        <li class="breadcrumb-item active" aria-current="page">Contact</li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>  <!--end col-->
                </div><!--end row-->
            </div> <!--end container-->
        </section><!--end section-->
        <!-- Hero End -->

        <!-- Shape Start -->
        <div class="position-relative">
            <div class="shape overflow-hidden text-white">
                <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
                </svg>
            </div>
        </div>
        <!--Shape End-->
        <!-- Start Contact -->
        <section class="section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6 pt-2">
                        <div class="card shadow rounded border-0">
                            <div class="card-body py-5">
                                <h4 class="card-title">Get In Touch !</h4>
                                <div class="custom-form mt-3">
                                    <div id="message">
                                        {% include 'main/flash_message.html' %}
                                    </div>
                                    <form method="post" name="contact-form" id="id_contact-form">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-md-12">
                                                <label class="form-label">Your Name <span class="text-danger">*</span></label>
                                                <div class="form-icon position-relative">
                                                    <i data-feather="user" class="fea icon-sm icons"></i>
                                                    <input name="name" id="id_name" type="text" class="form-control ps-5" placeholder="John Doe">
                                                </div>
                                            </div><!--end col-->

                                            <div class="col-md-12 mt-3">
                                                <label class="form-label">Your Email <span class="text-danger">*</span></label>
                                                <div class="form-icon position-relative">
                                                    <i data-feather="at-sign" class="fea icon-sm icons"></i>
                                                    <input name="email" id="id_email" type="email" class="form-control ps-5" placeholder="john.doe@gmail.com">
                                                </div>
                                            </div><!--end col-->
                                            <div class="col-md-12 mt-3">
                                                <label class="form-label">Message</label>
                                                <div class="form-group position-relative">
                                                    <textarea name="message" id="id_message" rows="4" class="form-control pl-5" placeholder="Your message here."></textarea>
                                                </div>
                                            </div>
                                            <div class="col-md-12 mt-4 mb-4">
                                                        <div class="g-recaptcha" data-sitekey="6LdosVQUAAAAAPLi6kp5c4Z8cjuN9d3Uu7j7tZxc"></div>

                                            </div>
                                        </div><!--end row-->
                                        <div class="row">
                                            <div class="col-sm-12 text-center d-grid gap-2">
                                                <input type="submit" id="submit" name="send" class="btn btn-primary btn-block" value="Send Message">
                                                <div id="simple-msg"></div>
                                            </div><!--end col-->
                                        </div><!--end row-->
                                    </form><!--end form-->
                                </div><!--end custom-form-->
                            </div>
                        </div>
                    </div><!--end col-->

                    <div class="col-lg-6 col-md-6 pl-md-3 pr-md-3 pt-2">
                        <div class="card map map-height-two rounded map-gray border-0">
                            <div class="card-body p-0">
                                <img src="{% static "xt/img/contact.jpg" %}" style="max-height: 600px;">
                            </div>
                        </div>
                    </div><!--end col-->
                </div><!--end row-->
            </div><!--end container-->

            <div class="container mt-100 mt-60">
                <div class="row">
                    <div class="col-md-4">
                        <div class="card contact-detail text-center border-0">
                            <div class="card-body p-0">
                                <div class="icon">
                                   <i class="far fa-comment-dots fa-3x text-primary"></i>

                                </div>
                                <div class="content mt-3">
                                    <h4 class="title font-weight-bold">Chat</h4>
                                    <p class="text-muted">Chat with a real person using the bottom right button.</p>
                                </div>
                            </div>
                        </div>
                    </div><!--end col-->

                    <div class="col-md-4 mt-4 mt-sm-0 pt-2 pt-sm-0">
                        <div class="card contact-detail text-center border-0">
                            <div class="card-body p-0">
                                <div class="icon">
                                    <i class="far fa-envelope-open-text fa-3x text-primary"></i>

                                </div>
                                <div class="content mt-3">
                                    <h4 class="title font-weight-bold">Email</h4>
                                    <p class="text-muted">If you have a file or larger text, email is preferred. In most cases, we respond within 4 hrs.</p>
                                    <a href="mailto:support@xpresstutor.com" class="text-primary">support@xpresstutor.com</a>
                                </div>
                            </div>
                        </div>
                    </div><!--end col-->

                    <div class="col-md-4 mt-4 mt-sm-0 pt-2 pt-sm-0">
                        <div class="card contact-detail text-center border-0">
                            <div class="card-body p-0">
                                <div class="icon">
                                    <i class="far fa-map-marker-alt fa-3x text-primary"></i>

                                </div>
                                <div class="content mt-3">
                                    <h4 class="title font-weight-bold">Location</h4>
                                    <p class="text-muted">Coffeen Ave, Sheridan, Wyoming, <br>USA 82801</p>
                                </div>
                            </div>
                        </div>
                    </div><!--end col-->
                </div><!--end row-->
            </div><!--end container-->
        </section><!--end section-->
        <!-- End contact -->
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>

{% endblock %}